## 付録2.2 Numpy入門

### NumPyの定義

#### ライブラリインポート

In [1]:
# ライブラリのインポート
import numpy as np

# numpyの浮動小数点の表示精度
np.set_printoptions(suppress=True, precision=4)

#### NumPyデータ定義

In [12]:
# NumPyデータ定義

# 1次元配列変数の定義
a = np.array([1, 2, 3, 4, 5, 6, 7])

# 2次元配列変数の定義
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9],[10,11,12]])

#### 内容表示

In [13]:
# 内容表示

# 1次元配列変数の表示
print(a)

# 2次元配列変数の表示
print(b)

[1 2 3 4 5 6 7]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


#### 要素数の確認

In [14]:
# 要素数の確認

# 1次元配列変数の表示
print(a.shape)

# 2次元配列変数の表示
print(b.shape)

# len関数の利用
print(len(a))
print(len(b))

(7,)
(4, 3)
7
4


### NumPyの操作

#### 特定列の抽出

In [24]:
# 特定列の抽出

# 0列
c = b[:,0]
print(c)

# [0,1]列
d = b[:,:2]
print(d)

[ 1  4  7 10]
[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]]


#### reshape関数

In [25]:
# reshape関数

l = np.array(range(12))
print(l)

# 3行4列に変換
m = l.reshape((3,4))
print(m)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


#### 統計関数

In [17]:
# 統計関数

print(f'元の変数: {a}')

a_sum = np.sum(a)
print(f'和: {a_sum}')

a_mean = np.mean(a)
print(f'平均: {a_mean}')

a_max = np.max(a)
print(f'最大値: {a_max}')

a_min = np.min(a)
print(f'最小値: {a_min}')

元の変数: [1 2 3 4 5 6 7]
和: 28
平均: 4.0
最大値: 7
最小値: 1


#### NumPy変数間の演算

In [19]:
# 二つのNumPy配列 ytとypの準備
yt = np.array([1, 1, 0, 1, 0, 1, 1, 0, 1, 1])
yp = np.array([1, 1, 0, 1, 0, 1, 1, 1, 1, 1])
print(yt)
print(yp)

[1 1 0 1 0 1 1 0 1 1]
[1 1 0 1 0 1 1 1 1 1]


In [20]:
# 配列の各要素を同時に比較する
w = (yt == yp)
print(w)

[ True  True  True  True  True  True  True False  True  True]


In [21]:
# 更にこの結果にsum関数をかける
print(w.sum())

9


#### ブロードキャスト機能

In [22]:
# ブロードキャスト機能
print(a)
c = (a - np.min(a)) / (np.max(a) - np.min(a))
print(c)

[1 2 3 4 5 6 7]
[0.     0.1667 0.3333 0.5    0.6667 0.8333 1.    ]


#### 数値配列の生成

In [23]:
# 数値配列の生成
x = np.linspace(-5, 5, 11)
print(x)

[-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]
